[package]
name = "olus"
description = "The Oluś programming language."
version = "0.1.0"
authors = ["Remco Bloemen <remco@wicked.ventures>"]
edition = "2018"

[dependencies]
log = "0.4.6"
stderrlog = "0.4.1"
structopt = "0.3"
parser = { path = "../parser" }
codegen = { path = "../codegen" }
